# Generated by Django 3.0.8 on 2020-07-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('asset', models.CharField(max_length=10)),
                ('optiontype', models.CharField(max_length=4)),
                ('strike', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('expmonthyear', models.DateField()),
                ('closing_price', models.DecimalField(decimal_places=3, max_digits=11)),
                ('change', models.DecimalField(decimal_places=3, max_digits=11)),
                ('volume', models.IntegerField()),
                ('max', models.DecimalField(decimal_places=3, max_digits=11)),
                ('min', models.DecimalField(decimal_places=3, max_digits=11)),
                ('trades', models.IntegerField()),
                ('fixing_price', models.DecimalField(decimal_places=3, max_digits=11)),
                ('open_interest', models.IntegerField()),
                ('optionsymbol', models.ForeignKey(default='option_symbol', on_delete=django.db.models.deletion.CASCADE, to='option_pricing.OptionSymbol')),
            ],
        ),
    ]
