# Generated by Django 3.0.8 on 2020-08-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0003_option_optionsymbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='closing_price',
            field=models.FloatField(),
        ),
    ]
