# Generated by Django 3.0.8 on 2020-08-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0004_auto_20200805_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionsymbol',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
