# Generated by Django 3.0.8 on 2020-08-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0006_auto_20200806_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='change',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='option',
            name='fixing_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='option',
            name='max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='option',
            name='min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='option',
            name='strike',
            field=models.FloatField(),
        ),
    ]
