# Generated by Django 3.0.8 on 2020-08-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0008_future'),
    ]

    operations = [
        migrations.RenameField(
            model_name='future',
            old_name='optionsymbol',
            new_name='futuresymbol',
        ),
        migrations.RemoveField(
            model_name='future',
            name='optiontype',
        ),
    ]
